name: BattleRoyale
main: com.gegenphase.battleroyale.startup.Startup
version: 1.2.1-03.10.2022a
api-version: 1.19
depend: [CrackShot, MoreItems]

commands:
  loot:
    usage: /<command>
    permission: battleroyale.loot
  game:
    usage: /<command>
    permission: battleroyale.game
  tipp:
    usage: /<command>
    permission: battleroyale.tipp

permissions:
  battleroyale.loot:
    default: op
  battleroyale.game:
    default: op
  battleroyale.tipp:
    default: true